### ISSUE TITLE
predict.coxph error when type="survival"

### ISSUE THREAD

**Issue by camontanezp** [therneau/survival#82] opened 2019-08-26 22:06 UTC
Dear developers and commmunity,

I'm getting an error when doing
_prediction.surv <- predict(cox.fit, newdata = new.data, type = "survival")_

I get: 
_Error in drop(pred) : object 'pred' not found_

I didn't get this error when using "lp", "risk" or "expected".

I would like to get the survival probability for a time-varying case. In case "survival" doesn't work, should I simply use _exp(-prediction.expected)_? 

I'm running R things in windows (see below):
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing

**Comment by therneau** [comment] 2019-09-06 01:24
That was a bug, caused by a simple typo.  Now fixed on my home machine, will be pushed tomorrow.

**Closed by therneau** 2019-09-06 01:24 UTC

**Comment by camontanezp** [comment] 2019-09-06 13:37
Awesome. Thanks!!!
